CREATE INDEX idx_admin_assistant_log_session ON admin_assistant_log(session_id, admin_id, id);
CREATE INDEX idx_aq_interview ON analysis_queue(interview_id);
CREATE INDEX idx_aq_owner ON analysis_queue(owner_id);
CREATE INDEX idx_aq_question_detail ON analysis_queue(question_detail_id);
CREATE INDEX idx_aq_status ON analysis_queue(status);
CREATE INDEX idx_aq_status_created ON analysis_queue(status, created_at);
CREATE INDEX idx_assistant_generations_visible ON assistant_generations(conversation_id, visible, created_at);
CREATE INDEX idx_cc_updated ON chat_conversations(updated_at);
CREATE INDEX idx_cc_user_status ON chat_conversations(user_id, status);
CREATE INDEX idx_cc_user_status_position ON chat_conversations(user_id, status, job_position);
CREATE INDEX idx_chat_candidate_sets_owner ON chat_candidate_sets(user_id, conversation_id, status, expires_at);
CREATE INDEX idx_chat_memories_provenance ON chat_memories(user_id, source_turn_id, content_hash);
CREATE INDEX idx_chat_side_effect_jobs_ready ON chat_side_effect_jobs(status, available_at);
CREATE INDEX idx_chat_turn_fence ON chat_turns(conversation_id, fence);
CREATE INDEX idx_chat_turn_request_fingerprint ON chat_turns(conversation_id, request_fingerprint);
CREATE INDEX idx_chat_turn_revision ON chat_turns(revision_of_message_id);
CREATE UNIQUE INDEX idx_chat_turn_running_conversation ON chat_turns(conversation_id) WHERE status = 'running';
CREATE INDEX idx_chat_turn_user_status ON chat_turns(user_id, status, created_at);
CREATE INDEX idx_cluster_review_state_status ON cluster_review_state(status, priority, updated_at);
CREATE INDEX idx_cluster_review_tasks_dispatch ON cluster_review_tasks(status, available_at, cluster_id);
CREATE INDEX idx_cluster_review_tasks_lease ON cluster_review_tasks(status, locked_until);
CREATE INDEX idx_cm_conversation ON chat_messages(conversation_id, created_at);
CREATE INDEX idx_cmem_user_active ON chat_memories(user_id, is_active);
CREATE INDEX idx_coding_playlist_user ON coding_playlists(user_id);
CREATE INDEX idx_coding_problem_owner ON coding_problems(owner_id);
CREATE INDEX idx_coding_sub_parent ON coding_submissions(parent_submission_id);
CREATE INDEX idx_coding_sub_problem ON coding_submissions(problem_id);
CREATE INDEX idx_coding_sub_user ON coding_submissions(user_id);
CREATE INDEX idx_ctt_conversation ON chat_tool_traces(conversation_id, created_at);
CREATE INDEX idx_email_codes_email ON email_verification_codes(email, purpose, used);
CREATE INDEX idx_iaq_conversation ON interview_asked_questions(conversation_id);
CREATE INDEX idx_iaq_user_question ON interview_asked_questions(user_id, question_id);
CREATE INDEX idx_interview_events_replay ON interview_events(conversation_id, id);
CREATE INDEX idx_interview_owner_status ON interview(owner_id, status);
CREATE INDEX idx_interview_url ON interview(url);
CREATE INDEX idx_interview_url_owner_deleted ON interview(url, owner_id, deleted_at);
CREATE INDEX idx_interview_url_sig ON interview(url_signature);
CREATE UNIQUE INDEX idx_interview_url_unique ON interview(url, owner_id) WHERE url IS NOT NULL AND url != "";
CREATE INDEX idx_jd_owner_status ON jd(owner_id, status);
CREATE INDEX idx_jd_url ON jd(url);
CREATE INDEX idx_jd_url_sig ON jd(url_signature);
CREATE UNIQUE INDEX idx_jd_url_unique ON jd(url, owner_id) WHERE url IS NOT NULL AND url != "";
CREATE INDEX idx_jobs_creator_type_status ON jobs(created_by, job_type, status);
CREATE INDEX idx_jobs_dispatch ON jobs(job_type, status, available_at, locked_until);
CREATE INDEX idx_jobs_parent ON jobs(parent_job_id, created_at);
CREATE INDEX idx_jobs_status ON jobs(status);
CREATE INDEX idx_jobs_type ON jobs(job_type);
CREATE INDEX idx_mcp_tokens_hash ON mcp_tokens(token_hash);
CREATE INDEX idx_merge_feedback_history ON merge_feedback(merge_history_id);
CREATE INDEX idx_merge_history_cat2 ON merge_history(cat2);
CREATE INDEX idx_merge_history_survivor ON merge_history(survivor_id);
CREATE INDEX idx_pm_created ON pipeline_metrics(created_at);
CREATE INDEX idx_pm_op ON pipeline_metrics(operation);
CREATE INDEX idx_practice_deck_items_order ON practice_deck_items(deck_id, sort_order, id);
CREATE INDEX idx_practice_deck_items_question ON practice_deck_items(question_bank_id);
CREATE INDEX idx_practice_deck_items_queue ON practice_deck_items(deck_id, sort_order, id, question_bank_id);
CREATE UNIQUE INDEX idx_practice_deck_key ON practice_decks(deck_key);
CREATE INDEX idx_practice_decks_owner ON practice_decks(owner_id, sort_order);
CREATE INDEX idx_practice_events_user_time ON practice_review_events(user_id, reviewed_at);
CREATE INDEX idx_qb_cluster_id ON question_bank(cluster_id);
CREATE INDEX idx_qb_deleted_owner_status ON question_bank(deleted_at, owner_id, status);
CREATE INDEX idx_qb_duplicate_of ON question_bank(duplicate_of);
CREATE INDEX idx_qb_job_position ON question_bank(job_position);
CREATE INDEX idx_qb_job_position_visibility ON question_bank(job_position, deleted_at, owner_id, status);
CREATE INDEX idx_qb_owner_status ON question_bank(owner_id, status);
CREATE INDEX idx_qb_owner_status_position ON question_bank(owner_id, status, job_position);
CREATE INDEX idx_qd_interview_question_type ON questions_detail(interview_id, question_type);
CREATE INDEX idx_qd_question ON questions_detail(question);
CREATE INDEX idx_qd_url ON questions_detail(url);
CREATE INDEX idx_qoi_deleted_at ON question_original_items(deleted_at);
CREATE INDEX idx_qoi_qb ON question_original_items(question_bank_id);
CREATE INDEX idx_qoi_text ON question_original_items(question_text);
CREATE INDEX idx_qois_deleted_at ON question_original_item_sources(deleted_at);
CREATE INDEX idx_qois_oi ON question_original_item_sources(original_item_id);
CREATE INDEX idx_qois_url ON question_original_item_sources(url);
CREATE INDEX idx_qp_position ON question_position(position_id);
CREATE INDEX idx_qp_position_question ON question_position(position_id, question_id);
CREATE INDEX idx_qs_deleted_at ON question_sources(deleted_at);
CREATE INDEX idx_qs_qb ON question_sources(question_bank_id);
CREATE INDEX idx_qs_url ON question_sources(url);
CREATE INDEX idx_quality_issue_fingerprint ON quality_issue(issue_fingerprint);
CREATE INDEX idx_quality_issue_review_version ON quality_issue(qb_id, review_version, status);
CREATE INDEX idx_question_variant_owners_qb ON question_variant_owners(question_bank_id);
CREATE INDEX idx_resume_user ON user_resumes(user_id);
CREATE INDEX idx_rt_family ON refresh_tokens(family_id);
CREATE INDEX idx_rt_jti ON refresh_tokens(jti);
CREATE INDEX idx_rt_user ON refresh_tokens(user_id);
CREATE INDEX idx_task_logs_created_at ON task_logs(created_at);
CREATE INDEX idx_task_logs_task_type ON task_logs(task_type);
CREATE UNIQUE INDEX idx_taxonomy_position_owner
            ON taxonomy(position_name, source, owner_id)
        ;
CREATE INDEX idx_uph_question ON user_practice_history(question_bank_id);
CREATE INDEX idx_uph_user ON user_practice_history(user_id);
CREATE INDEX idx_uph_user_date ON user_practice_history(user_id, created_at);
CREATE INDEX idx_uqr_due ON user_question_review(user_id, next_review_at);
CREATE INDEX idx_uqr_proficiency ON user_question_review(user_id, proficiency);
CREATE UNIQUE INDEX idx_uqr_user_question ON user_question_review(user_id, question_bank_id);
CREATE UNIQUE INDEX idx_uqv_user_question ON user_question_view(user_id, question_bank_id);
CREATE INDEX idx_uqv_user_starred ON user_question_view(user_id, is_starred);
CREATE UNIQUE INDEX idx_users_email_unique
        ON users(email) WHERE email IS NOT NULL AND email != ''
        ;
CREATE UNIQUE INDEX uq_interview_public_url_signature ON interview(url_signature) WHERE owner_id IS NULL AND deleted_at IS NULL AND url_signature != '';
CREATE UNIQUE INDEX uq_jd_public_url_signature ON jd(url_signature) WHERE owner_id IS NULL AND deleted_at IS NULL AND url_signature != '';
CREATE UNIQUE INDEX uq_jobs_idempotency ON jobs(job_type, idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_quality_issue_active_fingerprint ON quality_issue(issue_fingerprint) WHERE issue_fingerprint IS NOT NULL AND status IN ('pending', 'approved');
CREATE UNIQUE INDEX uq_quality_issue_review_version ON quality_issue(qb_id, review_version, issue_type, variant_key) WHERE review_version IS NOT NULL;
